import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "2.1.20"
    id("com.gradleup.shadow") version "9.3.0"
}

group = "me.udnek"
version = "1.0-SNAPSHOT"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

repositories {
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
    maven { url = uri("https://repo.papermc.io/repository/maven-public/") }
    maven { url = uri("https://oss.sonatype.org/content/groups/public/") }
    maven { url = uri("https://repo.maven.apache.org/maven2/") }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")
    compileOnly("org.apache.commons:commons-lang3:3.20.0")

    compileOnly(files("../CoreU/build/libs/CoreU-1.0-SNAPSHOT.jar"))
}

tasks {
    compileKotlin {
        compilerOptions.jvmTarget.set(JvmTarget.JVM_21)
    }
    compileJava {
        options.release.set(25)
    }
    shadowJar {
        archiveBaseName.set("JeiU")
        archiveClassifier.set("")
        archiveVersion.set(version.toString())
    }
}