name: JeiU
version: '${project.version}'
main: me.udnek.jeiu.JeiU
api-version: '1.21.11'
depend: [CoreU]
commands:
  recipe:
    description: "recipe"
    usage: "/recipe <item>"
    aliases: []
    permission-message: "You do not have permission to use this command"
  recipe_usages:
    description: "recipe_usages"
    usage: "/recipe_usages <item>"
    aliases: []
    permission-message: "You do not have permission to use this command"
  all_items:
    description: "all_items"
    usage: "/all_items"
    aliases: [items]
    permission-message: "You do not have permission to use this command"
  structure:
    description: "structure"
    usage: "/structure"
    aliases: []
    permission-message: "You do not have permission to use this command"

  u:
    description: "u"
    usage: "/u"
    aliases: []
    permission-message: "You do not have permission to use this command"
  loot_table:
    description: "loot_table"
    usage: "/loot_table"
    aliases: []
    permission-message: "You do not have permission to use this command"